### ISSUE TITLE
SI: FAQ content not importing

### ISSUE THREAD

**Issue by tonysandhu** [DNNCommunity/DNN.Faq#1]
Issue:
FAQ content does not import in Evoq 8.1.0

Steps to reproduce:
1) Create a new page on Evoq 8.1.0
2) Add the FAQ module to the page
3) Create an FAQ (Question & Answer)
4) Export the FAQ content
5) Create a new page
6) Add the FAQ module to the page
7) Import the FAQ content

Expected Result:
FAQ content should display after being imported

Actual Result:
FAQ content is not displayed

* Refer to the attached video demonstration [https://dnntracker.atlassian.net/browse/CONTENT-5408]

**Comment by EPTamminga** [comment]
Solved by PR
