### ISSUE TITLE
FAQ click/expand does not work after FAQ Category selection in DNN 8

### ISSUE THREAD

**Issue by rudgr** [DNNCommunity/DNN.Faq#10]
try:

- create 2 categories
- create a faq  in each category
- select second category
- click/expand second faq
- answer of first faq is displayed?

probably because telerik callback is replaced by dnn ClientAPI.GetCallbackEventReference and jsClientCallBackRef is not refreshed in dom after FAQ category selection?

**Comment by EPTamminga** [comment]
If you can supply a fix by a pull request, you are most welcome

**Comment by rudgr** [comment]
yup, working on it... :)

**Comment by rudgr** [comment]
pull requests send... Was already working on a DNN8 compatible version anyway...  afraid they got a little mixed up in the proces... will send more decent pull requests next time when I have more time. sorry

**Comment by EPTamminga** [comment]
Great! Yiur contributions als most welcome. When I am back from holiday, I will review, merge and release stuff.
BTW are you interested in doing a bit of coordination work on this module?

**Comment by rudgr** [comment]
sorry for my late reply! I'm abroad next week, let's discuss the coordination stuff after I return! :)

**Comment by joriscools** [comment]
Has this been allready fixed ?
Have the same issue.

thx

**Comment by EPTamminga** [comment]
Manually merged
