### ISSUE TITLE
Developed DNN Modules in 7.0 series, which is not workinng in new version of DNN 8.0 and above version

### ISSUE THREAD

**Issue by shrkntshu** [DNNCommunity/DNN.Faq#14]
I have developed some modules in DNN, which is working up to 7.02.02 version. When its installed in 8.00.00 version of DNN then its giving error in all view.ascx pages (A critical error has occurred. Please check the Event Viewer for further details as well as Object reference not set to an instance of an object). but not issue in add/edit page. so can you suggest how we can compatible old module in new version of DNN(8.00.00 or 8.0.3)
see below error...
Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Gooddogs.Modules.Dnn.QandA.Views.Result..ctor() at ASP.desktopmodules_qanda_views_result_ascx..ctor() in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\dnn8\a51b58ca\1564b738\App_Web_azliyz5c.3.cs:line 0 at __ASP.FastObjectFactory_app_web_azliyz5c.Create_ASP_desktopmodules_qanda_views_result_ascx() in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\dnn8\a51b58ca\1564b738\App_Web_azliyz5c.7.cs:line 0 at System.Web.UI.TemplateControl.LoadControl(IWebObjectFactory objectFactory, VirtualPath virtualPath, Type t, Object[] parameters) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by EPTamminga** [comment]
DNN8 has some breaking changes with respect to DNN7. Have a look at the release notes of DNN8:
http://dotnetnuke.codeplex.com/releases/view/621771

If you have a look at DNNF&L, you can see that there is a special updates release to make the module compliant with DNN8. https://github.com/DNNCommunity/DNN.FormAndList/releases

**Comment by shrkntshu** [comment]
Thanks for support , now my developed modules is working in DNN 8.0.0 version
