### ISSUE TITLE
Include release on Release page

### ISSUE THREAD

**Issue by hallmatt** [DNNCommunity/DNN.Faq#16]
I was able to download the code and make a build of the package - but non-developers will have difficulty doing this. Perhaps the download is available elsewhere...but the GitHub ReadMe should state where this is. All signs point to the releases page here on GitHub, but there isn't one there.

https://github.com/DNNCommunity/DNN.Faq/releases

A Release should be added and the ReadMe updated.

**Comment by EPTamminga** [comment]
Done
