### ISSUE TITLE
Install Aborted: DNN 8.4 Evoq Content Not Compatible

### ISSUE THREAD

**Issue by podkaynelives** [DNNCommunity/DNN.Faq#19]
1. From Host/Extensions page, click Install Extension Wizard button.
2. Select the downloaded FAQ zip file on local directory and click Next.

The following error message appears:

Failure	Install aborted - The module being installed is not compatible with this version of DNN. An upgrade to version 8.0.4 is required.

We have DNN 8.4 Evoq Content installed.

Please see attached screenshots.

Any help is appreciated - I really need to be able to update this extension.

[DNN-FAQ-Install-Screenshots.docx](https://github.com/DNNCommunity/DNN.Faq/files/1072238/DNN-FAQ-Install-Screenshots.docx)

**Comment by EPTamminga** [comment]
I see nothing special wrong with the install manifest specification line.
You could try an install after removing these 3 lines from the DNN_FAQs.dnn file in the zip:
      <dependencies>
        <dependency type="CoreVersion">08.00.04</dependency>
      </dependencies>

**Comment by podkaynelives** [comment]
That worked perfectly, thanks!
