### ISSUE TITLE
FAQ:Index is not working after upgraded

### ISSUE THREAD

**Issue by sytan79** [DNNCommunity/DNN.Faq#20]
We had updated our FAQ module from v5.0.2 to v5.4.0 but there are issues where the [FAQ:INDEX] displayed as 0 instead of numbering or bullets. 
![q2-dnn faq](https://user-images.githubusercontent.com/30623084/28821217-2cc6ad7c-76e7-11e7-81c7-6b067431dd47.png)

**Comment by valadas** [comment]
I cannot reproduce this issue using the current code, please try the 5.4.1 version when released (today or tomorrow probably) and if it is still an issue, please submit a new issue.
