### ISSUE TITLE
the [INDEX] token loads as zero (0)

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/DNN.Faq#32]
## Describe the bug
Admittedly I need to test this on multiple other DNN instances and possibly on a new install vs an upgrade install, however, what I've experienced is that in a site which upgraded from older FAQ module version up to 5.4.0 and 5.4.1 does not render the [INDEX] token correctly. In a list of displayed FAQ items, it will display the number zero (0) in every instance.

## To Reproduce
1. In the Question Template, enter a value such as this:
<div Class="Normal">
<b>Q [INDEX] . [QUESTION]</b>
</div>

2. Load a list of FAQ questions and at this point it would display as:
Q 0 . QuestionHere

## Expected behavior
It should be displaying the number count of FAQ questions as in
Q1
Q2
Q3
Q4
etc

## Additional context
Experienced in a DNN instance that moved from Evoq 7x to Evoq 8.5. The FAQ module moved from FAQ 4.4.0 up to final 5.4.1

**Comment by valadas** [comment]
Thanks for the clarification.

**Comment by nvisionative** [comment]
I can confirm this does not work correctly on a fresh install either.  I tested using the new token format **[FAQ:INDEX]** as well.  I set up the project on my dev machine but have yet to be able to debug properly.  Hopefully, I will get the issues resolved on my machine so that symbols are loaded properly.

**Comment by nvisionative** [comment]
Okay, I have isolated [the problematic area of code](https://github.com/DNNCommunity/DNN.Faq/blob/development/FAQs.ascx.cs#L314-L356).  Once I am able to debug properly, I should be able to get the code fixed and make a pull request.  In the meantime, you will see that enabling **Show Question Categories** allows the [FAQ:INDEX] token values to be hydrated.
