### ISSUE TITLE
Using on Evoq 9.2 complains of missing Telerik dll

### ISSUE THREAD

**Issue by djfenske** [DNNCommunity/DNN.Faq#33]
Install of FAQ 5.4.01 on a clean install of Evoq 9.2 completes successfully. But when adding to a page for the first time, the error message indicates that it needs a Telerik dll that has apparently been deprecated:

`Error: FAQs is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Could not load file or assembly 'Telerik.Web.UI' or one of its dependencies. The system cannot find the file specified. ---> `

**Comment by EPTamminga** [comment]
Copy the Telerik dll from a previous Evoq release into the bin\ folder.

**Comment by djfenske** [comment]
I also ended up needing to copy in the DotNetNuke.Web.Deprecated.dll from a Platform 9.2 install, but then it worked. Thank you.

**Comment by EPTamminga** [comment]
@djfenske Thank you for your feedback. Good to read that it is working. 
The Telerik thing has a history. It does not have to do with security vulnerability atm, but (to make a long story short), the intention is to make DNN (DNNPlatform & Evoq) not depending on the Telerik dll anymore. 
Evoq and DNNPlatform 9.2 have succeeded in this 'clean out of the box', additional modules are still on the move to that point.
