### ISSUE TITLE
FAQ 5.1.1 Fails on DNN 8.0.0

### ISSUE THREAD

**Issue by TopCat6** [DNNCommunity/DNN.Faq#6]
After upgrading from DNN 7.4.2 to 8.0.0, the FAQ module 5.1.1 gives this error:

Error: FAQs is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Unknown server tag 'dnn:DnnListBox'. ---> System.Web.HttpParseException: Unknown server tag 'dnn:DnnListBox'. ---> System.Web.HttpParseException: Unknown server tag 'dnn:DnnListBox'. ---> System.Web.HttpException: Unknown server tag 'dnn:DnnListBox'. at System.Web.UI.TagPrefixTagNameToTypeMapper.System.Web.UI.ITagNameToTypeMapper.GetControlType(String tagName, IDictionary attribs) at System.Web.UI.MainTagNameToTypeMapper.GetControlType2(String tagName, IDictionary attribs, Boolean fAllowHtmlTags)

Full stack trace available at: http://www.dnnsoftware.com/forums/forumid/27/threadid/527896/scope/posts

**Comment by ahawkins110** [comment]
I am also having the same issue. Not sure how to compile all the updates you have here into a usable install. Thanks in advance.

**Comment by leedrake** [comment]
I understand that there's a fix for this waiting on a merge/release from someone who was on vacation a week ago?  When complete could I request that a link to the current version zip be added to the releases page as is proper format similar to for instance dnn.feedback?

**Comment by rstordeur** [comment]
I have the same problem and error message on DNN 8.0.3.  Any idea when a fix will be released?

**Comment by EPTamminga** [comment]
I think that there are PR's that will make DNN.Faq compliant with DNN8. 
Is there a developer around who is willing to do the merge/build & test?

**Comment by thenotandy** [comment]
The "Release 05.03.00" PR seems to be working successfully in DNN 8.0.3.

**Comment by TopCat6** [comment]
I agree, the "Release 05.03.00" in the Pull Requests seems to work fine, with no error messages. Can we now make a formal "Release" for it under "releases" on the DNN.Faq Code page?

**Comment by EPTamminga** [comment]
Fine with me. Pleas have a go for the release.

**Comment by EPTamminga** [comment]
05.04.00 DNN 8 compliant version released
